# Generated by Django 5.0.7 on 2024-10-07 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('passwrd', models.CharField(default='pbkdf2_sha256$720000$4Jksu8ArU7ZyUsJL4Gc574$OmcKTq1sNGsYtEUjIiAzTGLjVfSQJEGFEYIplOsnbsU=', max_length=225)),
                ('dob', models.DateField()),
                ('isAdmin', models.BooleanField(default=False)),
                ('isCampOrg', models.BooleanField(default=False)),
                ('isHosp', models.BooleanField(default=False)),
                ('belongs', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('passwrd', models.CharField(default='pbkdf2_sha256$720000$scqfFjSlAxUzYRTh9wQ1RR$+EazrG680Tmyz8ItSxGbUXq8QSW6LevbPImISEx1hIs=', max_length=225)),
                ('dob', models.DateField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('addr', models.CharField(max_length=225)),
                ('blood_type', models.CharField(choices=[('A+', 'Ax'), ('A-', 'A '), ('B+', 'Bx'), ('B-', 'B '), ('O+', 'Ox'), ('O-', 'O '), ('AB+', 'Abx'), ('AB-', 'Ab ')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=225)),
                ('loc', models.CharField(max_length=225)),
                ('capacity', models.IntegerField()),
                ('a_plus', models.IntegerField(default=0)),
                ('a_minus', models.IntegerField(default=0)),
                ('b_plus', models.IntegerField(default=0)),
                ('b_minus', models.IntegerField(default=0)),
                ('ab_plus', models.IntegerField(default=0)),
                ('ab_minus', models.IntegerField(default=0)),
                ('o_plus', models.IntegerField(default=0)),
                ('o_minus', models.IntegerField(default=0)),
                ('owned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=225)),
                ('loc', models.CharField(max_length=225)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('owned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini.admin')),
            ],
        ),
    ]
