# Generated by Django 5.0.7 on 2024-10-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='passwrd',
            field=models.CharField(default='pbkdf2_sha256$720000$vGy9yFl8apnIhmE1Wsr8JO$GmLxxT3xE8iwV+L1EzqxAKRms5LSPCfVEwyLMfi9Fm0=', max_length=225),
        ),
        migrations.AlterField(
            model_name='donor',
            name='passwrd',
            field=models.CharField(default='pbkdf2_sha256$720000$GJkwtZQC2cS4p5l2ZCeURz$/urRGRHZayU3QGDumfszAV4MbeFfK9vAqvBOb2DxM/k=', max_length=225),
        ),
    ]
