# Generated by Django 5.0.7 on 2024-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0002_alter_admin_passwrd_alter_donor_passwrd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='passwrd',
            field=models.CharField(default='pbkdf2_sha256$720000$MS9CVwF7twb6YNnBzNRGiZ$InkSDLhZHC3lnJZ8Qukqa/6Riqb+DzVjjbW9JG/pGag=', max_length=225),
        ),
        migrations.AlterField(
            model_name='donor',
            name='passwrd',
            field=models.CharField(default='pbkdf2_sha256$720000$fuksb9zixPzoaWpDVeMMY8$Hsw8OuGACoVlThdiJVpacNp65L6BGMueFykTY2Ufnes=', max_length=225),
        ),
    ]
