# Generated by Django 5.0.7 on 2024-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0003_alter_admin_passwrd_alter_donor_passwrd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='passwrd',
            field=models.CharField(default='pbkdf2_sha256$720000$ekmu46peCyjWcv58t0aN1v$Ze8PKlI97qNhEsrtJc9jGA69JcfLVCQ5q+2kqYH/vl4=', max_length=225),
        ),
        migrations.AlterField(
            model_name='donor',
            name='passwrd',
            field=models.CharField(default='pbkdf2_sha256$720000$4u9cLTOFkLPCGKinZAEbak$PUV/2yL3kk2BSJcwQUJivdkc3bOjTjb6v08wQHyxJZo=', max_length=225),
        ),
    ]
