# Generated by Django 5.0.7 on 2024-10-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0005_alter_admin_passwrd_alter_donor_passwrd_campreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='passwrd',
            field=models.CharField(default='pbkdf2_sha256$720000$9z4lEyUZcwqlKWeoxgL2js$BoLKp85tWCpwhzrraESfT3VvWeT1tX0paB07Sx3t6Tw=', max_length=225),
        ),
        migrations.AlterField(
            model_name='donor',
            name='passwrd',
            field=models.CharField(default='pbkdf2_sha256$720000$AjRHdFEVFeex91GTxoKAVU$qaHbS+spKbm0pyyAN7WhAu57Eo0/bIMeBwXyc+gThYw=', max_length=225),
        ),
    ]
