# Generated by Django 5.0.7 on 2024-10-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0006_alter_admin_passwrd_alter_donor_passwrd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='passwrd',
            field=models.CharField(default='pbkdf2_sha256$720000$djgOi5Nvl8aHQwTqNHiUeX$3XJP90S2B8YW7CfPsPw7LOWvKv+752/vlmfW6jIRC9U=', max_length=225),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O+', 'O+'), ('B+', 'B+'), ('B-', 'B-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donor',
            name='passwrd',
            field=models.CharField(default='pbkdf2_sha256$720000$3UTetVIFo3XLjCidZxloVU$m26r2oPlEnLlkoG+mJFQmTTIfVn3uuK4rw63bWkEJC4=', max_length=225),
        ),
    ]
