# Generated by Django 5.0.7 on 2024-10-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini', '0007_alter_admin_passwrd_alter_donor_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='passwrd',
            field=models.CharField(default='pbkdf2_sha256$720000$jSNd64jQ075N9pOJPkvt0v$xwjg6QIYj1Us/bxS61bk0rjbXxJUEGb3c3A51hZWrIg=', max_length=225),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O+', 'O+'), ('B+', 'B+'), ('BA-', 'B-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donor',
            name='passwrd',
            field=models.CharField(default='pbkdf2_sha256$720000$XbVH681MA1zFoNVWCXwl3C$vXq5J4tMU7YPXKa8MxvfC7CxC7Z/cxq6y6CAjSFPSQI=', max_length=225),
        ),
    ]
